using DvlDevTools.Http.Attributes;

namespace DvlDevTools.Http.Enumeration
{
	public enum AcceptType
	{
		[HeaderDisplayName("application/atom+xml")]
		ApplicationAtomXml,
		[HeaderDisplayName("application/ecmascript")]
		ApplicationEcmaScript,
		[HeaderDisplayName("application/json")]
		ApplicationJson,
		[HeaderDisplayName("application/vnd.api+json")]
		ApplicationVndApiJson,
		[HeaderDisplayName("application/javascript")]
		ApplicationJavaScript,
		[HeaderDisplayName("application/octet-stream")]
		ApplicationOctetStream,
		[HeaderDisplayName("application/ogg")]
		ApplicationOgg,
		[HeaderDisplayName("application/pdf")]
		ApplicationPdf,
		[HeaderDisplayName("application/postscript")]
		ApplicationPostScript,
		[HeaderDisplayName("application/rdf+xml")]
		ApplicationRdfXml,
		[HeaderDisplayName("application/rss+xml")]
		ApplicationRssXml,
		[HeaderDisplayName("application/soap+xml")]
		ApplicationSoapXml,
		[HeaderDisplayName("application/font-woff")]
		ApplicationFontWoff,
		[HeaderDisplayName("application/x-yaml")]
		ApplicationXYaml,
		[HeaderDisplayName("application/xhtml+xml")]
		ApplicationXHtmlXml,
		[HeaderDisplayName("application/xml")]
		ApplicationXml,
		[HeaderDisplayName("application/xml-dtd")]
		ApplicationXmlDtd,
		[HeaderDisplayName("application/xop+xml")]
		ApplicationXopXml,
		[HeaderDisplayName("application/zip")]
		ApplicationZip,
		[HeaderDisplayName("application/gzip")]
		ApplicationGZip,
		[HeaderDisplayName("application/graphql")]
		ApplicationGraphQl,
		[HeaderDisplayName("application/x-www-form-urlencoded")]
		ApplicationXWwwFormUrlEncoded,
		[HeaderDisplayName("audio/basic")]
		AudioBasic,
		[HeaderDisplayName("audio/L24")]
		AudioL24,
		[HeaderDisplayName("audio/mp4")]
		AudioMp4,
		[HeaderDisplayName("audio/mpeg")]
		AudioMpeg,
		[HeaderDisplayName("audio/ogg")]
		AudioOgg,
		[HeaderDisplayName("audio/vorbis")]
		AudioVorbis,
		[HeaderDisplayName("audio/vnd.rn-realaudio")]
		AudioVndRnRealAudio,
		[HeaderDisplayName("audio/vnd.wave")]
		AudioVndWave,
		[HeaderDisplayName("audio/webm")]
		AudioWebm,
		[HeaderDisplayName("image/gif")]
		ImageGif,
		[HeaderDisplayName("image/jpeg")]
		ImageJpeg,
		[HeaderDisplayName("image/pjpeg")]
		ImagePJpeg,
		[HeaderDisplayName("image/png")]
		ImagePng,
		[HeaderDisplayName("image/svg+xml")]
		ImageSvgXml,
		[HeaderDisplayName("image/tiff")]
		ImageTiff,
		[HeaderDisplayName("message/http")]
		MessageHttp,
		[HeaderDisplayName("message/imdn+xml")]
		MessageImdnXml,
		[HeaderDisplayName("message/partial")]
		MessagePartial,
		[HeaderDisplayName("message/rfc822")]
		MessageRfc822,
		[HeaderDisplayName("multipart/mixed")]
		MultipartMixed,
		[HeaderDisplayName("multipart/alternative")]
		MultipartAlternative,
		[HeaderDisplayName("multipart/related")]
		MultipartRelated,
		[HeaderDisplayName("multipart/form-data")]
		MultipartFormData,
		[HeaderDisplayName("multipart/signed")]
		MultipartSigned,
		[HeaderDisplayName("multipart/encrypted")]
		MultipartEncrypted,
		[HeaderDisplayName("text/cmd")]
		TextCmd,
		[HeaderDisplayName("text/css")]
		TextCss,
		[HeaderDisplayName("text/csv")]
		TextCsv,
		[HeaderDisplayName("text/html")]
		TextHtml,
		[HeaderDisplayName("text/plain")]
		TextPlain,
		[HeaderDisplayName("text/vcard")]
		TextVCard,
		[HeaderDisplayName("text/xml")]
		TextXml
	}
}
